ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS cpf text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cep text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rua text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS complemento text NOT NULL DEFAULT '';
